server:
  port: 8010
  compression:
    enabled: true
#    mime-types:
#      - application/json
#      - application/xml
#      - text/html
#      - text/xml
#      - text/plain
    min-response-size: 1
#logging:
#  level:
#     root: debug
# Nacos registry address
dubbo:
  application:
    id: ${spring.application.name}
    qos-enable: false
  registry:
    #address: nacos://127.0.0.1:8848
    address: spring-cloud://localhost
  cloud:
    # The subscribed services in consumer side
    subscribed-services:  ${spring.application.name},xc-service
 # provider:
    #host: 127.0.0.1
    #?namespace=cbe53515-f2ac-4ce1-bf54-c3fd9259a1da
  protocol:
#    name: nacos
    name: dubbo
    port: -1


spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        ip: ${NACOS_REGIST_IP:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
    bus:
      id: ${spring.application.name}:${server.port}
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
        springCloudBusOutput:
          destination: springCloudBus
        input:
          group: xc-binder-group
          destination: xc-binder-topic
          content-type: application/json
      rocketmq:
        binder:
          nameServer: ${ROCKET_MQ_HOST:127.0.0.1:9876}

    inetutils:
      preferred-networks: ${spring.networks:}





##请求和响应GZIP压缩支持
feign:
  hystrix:
    enabled: true #是否开启熔断
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 4000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试


ignore:
  startWith: /user/login,/user/regist,/test,/user/getCode,/xc/executorQuartz,/quartz,/getCache

xc:
  executor:
    enabled: true #启动线程池
